py_app/urls.py
from django.urls import path
from py_app import views

app_name = 'py_app'

urlpatterns = [
    path('', views.base, name='base'),
    path('help', views.help, name='help'),
    path('register', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
]

pyprice/urls.py
from django.contrib import admin
from django.urls import path, include
from py_app import views


urlpatterns = [
    path('', include('py_app.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
]

py_app/models.py
from django.db import models
from django.contrib.auth.models import User

py_app/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User


def check_num_positivo(value):
    if value < 0:
        raise forms.ValidationError("El valor debe ser positivo")


class FormName(forms.Form):
    ref = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),validators=[validators.MaxLengthValidator(25)])
    precioArs = forms.IntegerField(widget=forms.NumberInput(attrs={'class': 'form-control', 'type': 'number'}),validators=[check_num_positivo])


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

py_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from . import forms
from py_app.forms import UserForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
import requests
import json

historial = []

def base(request):
    response = requests.get('https://www.dolarsi.com/api/api.php?type=valoresprincipales')
    data = json.loads(response.text)
    dolarOficial = float(data[0]['casa']['venta'].replace(",","."))
    dolarBlue = float(data[1]['casa']['venta'].replace(",","."))
    dolarCCL = float(data[3]['casa']['venta'].replace(",","."))
    dolarBolsa = float(data[4]['casa']['venta'].replace(",","."))
    form = forms.FormName()
    context = {}
    context["form"] = form
    context["oficial"] = dolarOficial
    context["blue"] = dolarBlue
    context["ccl"] = dolarCCL
    context["bolsa"] = dolarBolsa
    if request.method == 'POST' and 'submit' in request.POST:
        form = forms.FormName(request.POST)
        if form.is_valid():

            precioOficial = round((form.cleaned_data['precioArs'] / dolarOficial),2)
            precioBlue = round((form.cleaned_data['precioArs'] / dolarBlue),2)
            precioCCL = round((form.cleaned_data['precioArs'] / dolarCCL),2)
            precioBolsa = round((form.cleaned_data['precioArs'] / dolarBolsa),2)

            new_entry = {
                "ref":form.cleaned_data['ref'],
                "pars":form.cleaned_data['precioArs'],
                "poficial": precioOficial,
                "pblue": precioBlue,
                "pccl": precioCCL,
                "pbolsa": precioBolsa,
            }

            historial = request.session.get('historial', [])
            historial.insert(0, new_entry)
            if len(historial) > 5:
                historial = historial[:5]
            request.session['historial'] = historial
            messages.success(request, 'Referencia Guardada Correctamente')
            return HttpResponseRedirect(reverse('py_app:base'))

    if request.method == 'POST' and 'clear' in request.POST:
        if 'historial' in request.session:
            del request.session['historial']
            messages.success(request, 'Historial Eliminado')

    historial = request.session.get('historial',[])
    context["historial"] = historial

    return render(request, 'py_app/base.html',context)


def help(request):
    helpdict = {'help_insert': 'Help Page'}
    return render(request, 'py_app/help.html', context=helpdict)

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors)
    else:
        user_form = UserForm()

    return render(request,'py_app/registration.html',{'user_form':user_form,'registered':registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('py_app:base'))
            else:
                return HttpResponseRedirect("Cuenta no activa")
        else:
            print("Fallo de Login")
            return HttpResponse("Login Invalido")
    else:
        return render(request,'py_app/login.html',{})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('py_app:base'))

templates/py_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
</head>
<body>
    <nav class='navbar navbar-expand-lg navbar-light bg-light'>
        <span class="navbar-brand" href="#"><img src="{% static '/images/money_with_wings.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">  PyPrice</span>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'py_app:help'%}">Help</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}">Logout</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'py_app:register'%}">Registrarse</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'py_app:user_login'%}">Ingresar</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block body_block %}
    {% endblock %}
    <div class="container mt-5 mb-5 d-flex justify-content-center">
        {% if user.is_authenticated %}
        <div class="left-div">
                    <h4>Ingrese una referencia y un monto en pesos</h4>
                    <form method="POST">
                        <div class="form-group">
                            {{form.as_p}}
                            {% csrf_token %}
                            <input type="submit" name="submit" class="btn btn-primary" value="Calcular Precio USD">
                            <input type="submit" name="clear" class="btn btn-primary" value="Borrar Historial" formnovalidate>
                        </div>
                    </form>
        </div>
        {% endif %}
        <div class="right-div">
            <table class="table table-dark mb-0">
                <thead>
                    <tr>
                        <th scope="col">Dolar</th>
                        <th scope="col">Cotización</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Oficial</td>
                        <td>{{oficial}}</td>
                    </tr>
                    <tr>
                        <td>Blue</td>
                        <td>{{blue}}</td>
                    </tr>
                    <tr>
                        <td>CCL</td>
                        <td>{{ccl}}</td>
                    </tr>
                    <tr>
                        <td>Bolsa</td>
                        <td>{{bolsa}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="historial">
        <h2>Historial</h2>
        <table class="table table-dark mb-0">
                <thead>
                    <tr>
                        <th scope="col">Referencia</th>
                        <th scope="col">Precio ARS</th>
                        <th scope="col">Precio Oficial</th>
                        <th scope="col">Precio Blue</th>
                        <th scope="col">Precio CCL</th>
                        <th scope="col">Precio Bolsa</th>
                    </tr>
                </thead>
            <tbody>
                {% for entry in historial %}
                <tr>
                    <td>{{ entry.ref }}</td>
                    <td>{{ entry.pars }}</td>
                    <td>{{ entry.poficial }}</td>
                    <td>{{ entry.pblue }}</td>
                    <td>{{ entry.pccl }}</td>
                    <td>{{ entry.pbolsa }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</body>
</html>

templates/py_app/help.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>HELP PAGE</title>
    </head>
    <body>
        {{ help_insert }}
    </body>
</html>

templates/py_app/home.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
<h1>Ingrese una referencia y un monto en pesos</h1>
<div class="container">
    <form method="POST">
        {{form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Calcular Precio USD">
    </form>
</div>
</body>
</html>

templates/py_app/login.html
{% extends "py_app/base.html" %}
{% block body_block %}


<div class="container mt-5 mb-5 d-flex justify-content-center">
    <form action="{% url 'py_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Usuario:</label>
        <input type="text" name="username" placeholder="Ingrese su Usuario">

        <label for="password">Clave:</label>
        <input type="password" name="password" placeholder="Ingrese su Clave">

        <input type="submit" name="" value="Login">
    </form>
</div>


{% endblock %}

templates/py_app/registration.html
{% extends "py_app/base.html" %}
{% block body_block %}


<div class="container mt-5 mb-5 d-flex justify-content-center">
    {% if registered %}
    <h1>Ya estas registrado</h1>
    {% else %}
        <h2>Llene el formulario</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        <input type="submit" name=" " value="Registrarse">
    </form>
    {% endif %}
</div>


{% endblock %}